dataset_path: C:\Users\numan\Downloads\Aqua\dataset
data_yaml: C:\Users\numan\Downloads\Aqua\dataset\data.yaml
img_size: 640
model: yolov8n.pt
num_classes: 6
classes: ['BIODEGRADABLE', 'CARDBOARD', 'GLASS', 'METAL', 'PAPER', 'PLASTIC']